#! /bin/sh

sxhkd &
ibus-daemon -drx
mailspring --background &
libinput-gestures-setup start 
feh --bg-fil $HOME/Pictures/bg.jpg

bspc monitor eDP-1 -d 1 2 3 4 5 
bspc monitor DP-3 -d 6 7 8 9 0

$HOME/Workspace/global/dotfiles/polybar/styles/launch.sh

bspc config border_width         2
bspc config window_gap          16

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
